include $(THEOS)/makefiles/common.mk

TWEAK_NAME = MASQ11
MASQ11_FILES = 11.xm
MASQ11_INSTALL_PATH = /Library/TweakInject
MASQ11_FRAMEWORKS = UIKit CoreGraphics
MASQ11_PRIVATE_FRAMEWORKS = MediaRemote
MASQ11_CFLAGS = -fobjc-arc
include $(THEOS_MAKE_PATH)/tweak.mk
